// AUTO-GENERATED by update-schema.mjs. Do not edit by hand.

import * as AuthDrizzleSchema from '../schema/drizzle/auth.drizzle.schema';
import * as EmailDrizzleSchema from '../schema/drizzle/email.drizzle.schema';
import * as EnumDrizzleSchema from '../schema/drizzle/enum.drizzle.schema';
import * as RelationDrizzleSchema from '../schema/drizzle/relation.drizzle.schema';

const schema = {
	...AuthDrizzleSchema,
	...EmailDrizzleSchema,
	...EnumDrizzleSchema,
	...RelationDrizzleSchema,
};

export default schema;
