// AUTO-GENERATED by update-schema.mjs. Do not edit by hand.

import * as AuthDrizzleSchema from '../schema/drizzle/auth.drizzle.schema';
import * as EnumDrizzleSchema from '../schema/drizzle/enum.drizzle.schema';

const schema = {
	...AuthDrizzleSchema,
	...EnumDrizzleSchema,
};

export default schema;
